import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { createClient } from '../prismicio'
import * as prismicH from '@prismicio/helpers'

const inter = Inter({ subsets: ['latin'] })
import styles from '../styles/Home.module.css'

const Page = ({ page, navigation, settings }) => {

    console.log(page)
    return (
        <>
        <Head>
            <title>Page | {settings.data.name} | {settings.data.title}</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
            hello
            
        </main>
        </>
    )
}

export default Page

export async function getStaticProps({ params, previewData }) {
    const client = createClient({ previewData })

    const page = await client.getByUID('page', params.uid)
    const navigation = await client.getSingle('navigation')
    const settings = await client.getSingle('settings')

    return {
        props: {
            page,
            navigation,
            settings
        },
    }
}

export async function getStaticPaths() {
  const client = createClient()

  const pages = await client.getAllByType('page')


  return {
    paths: pages.map((page) => prismicH.asLink(page)),
    fallback: false,
  }
}