import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { createClient } from '../prismicio'

import styles from '../styles/Home.module.css'


const inter = Inter({ subsets: ['latin'] })

export default function Home({ page, settings }) {
    console.log(page)
    console.log(settings)
    return (
        <>
        <Head>
            <title>{settings.data.name} | {settings.data.title}</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
            hello
            
        </main>
        </>
    )
}

export async function getStaticProps({ previewData }) {
    const client = createClient({ previewData })   
    const page =  await client.getByUID('page', 'home')
    const settings = await client.getSingle('settings')
  
    return {
        props: {
            page,
            settings
        },
    }
}
